# Lançadores que devem ser ocultos do menu de aplicativos
launchers_to_hide+=("thunar.desktop")
launchers_to_hide+=("xfce4-session-logout.desktop")
launchers_to_hide+=("vim.desktop")
launchers_to_hide+=("debian-uxterm.desktop")
launchers_to_hide+=("debian-xterm.desktop")
launchers_to_hide+=("yad-icon-browser.desktop")
launchers_to_hide+=("xfce4-about.desktop")
launchers_to_hide+=("display-im6.q16.desktop")
launchers_to_hide+=("xfce4-appfinder.desktop")
launchers_to_hide+=("xfce4-run.desktop")
launchers_to_hide+=("settings-hardware-sound.desktop")
launchers_to_hide+=("xfhelp4.desktop")
launchers_to_hide+=("com.gexperts.Tilix.desktop")
